### ISSUE TITLE
Node.js 12 actions are deprecated still showing

### ISSUE THREAD

**Issue by drey0143143** [terraform-docs/gh-actions#101] opened 2023-01-20 01:34 UTC
I'm getting the following message when use "terraform-docs/gh-actions@v1.0.0"
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by khos2ow** [comment] 2024-03-23 00:43
Closing this in favor of its duplicate of #97 which is fixed in #94.

**Closed by khos2ow** 2024-03-23 00:43 UTC
Labels: bug
